services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./app:/app/app
      - ./uploaded_files:/app/uploaded_files
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - db
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 7G
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama
    entrypoint: ["/bin/ollama"]
    command: serve
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_GPU_LAYERS=24
      - OLLAMA_MODELS=/root/.ollama/models
      - CUDA_VISIBLE_DEVICES=0
      - OLLAMA_KEEP_LOADED=true
    networks:
      - app-network

  db:
    image: ankane/pgvector:v0.5.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:

 
