name: ollama_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - numpy=1.26.3
  - pip:
    # Core dependencies
    - python-dotenv==1.0.0
    - asyncpg==0.29.0
    - httpx[http2]==0.26.0
    - fastapi==0.109.0
    - pydantic>=2.0.0,<3.0.0
    - uvicorn==0.27.0
    - psycopg2-binary==2.9.9
    - python-multipart==0.0.6
    - requests==2.31.0
    # LlamaIndex
    - llama-index-core>=0.10.0
    # Data processing
    - pandas>=2.0.0
    - scikit-learn>=1.3.0
    - tiktoken